export const data = [
  { linkText: "home", withDropDown: false },
  {
    linkText: "about us",
    withDropDown: true,
    details: [
      "company information",
      "our board",
      "management",
      "vision & mission",
      "our goal",
      "our philosophy",
      "departments",
      "divisional structure",
      "post office structure",
      "mail route network",
    ],
  },
  {
    linkText: "services",
    withDropDown: true,
    details: [
      "counters",
      "ems/parcels",
      "mails",
      "e-commerce and logistics",
      "financial services",
      "workshop & property",
      "nigerian postal institute",
    ],
  },
  { linkText: "news", withDropDown: false },
  {
    linkText: "media",
    withDropDown: true,
    details: ["photo gallery", "resources"],
  },
  {
    linkText: "quick tools",
    withDropDown: true,
    details: [
      "postcode finder",
      "postoffice finder",
      "counter automation",
      "po box registration",
      "post alert registration",
      "buy insurance cover",
    ],
  },
  {
    linkText: "contact",
    withDropDown: true,
    details: ["corporate address", "feedback"],
  },
];
